-- AlterTable
ALTER TABLE "Site" ADD COLUMN     "primaryColor" TEXT NOT NULL DEFAULT '#0f172a',
ADD COLUMN     "radius" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "theme" TEXT NOT NULL DEFAULT 'AUTO';
